--
-- Update units in the TAP Schema.
--
-- jenkinsd 2019.11.20
--

UPDATE TAP_SCHEMA.COLUMNS11
SET UNIT = 'deg'
WHERE LOWER(COLUMN_NAME) = 's_resolution';

UPDATE TAP_SCHEMA.COLUMNS11
SET UNIT = 'deg'
WHERE LOWER(COLUMN_NAME) = 's_fov';

UPDATE TAP_SCHEMA.COLUMNS11
SET UNIT = 'm'
WHERE LOWER(COLUMN_NAME) = 'em_resolution';
