
DROP INDEX SPATIAL_BOUNDS_IDX_A;
DROP INDEX SPATIAL_BOUNDS_IDX_B;
delete from user_sdo_geom_metadata;

-- Populate the SPATIAL_BOUNDS column based on the current footprint values. 
-- Takes roughly two hours to complete in ESO's dev / test database
UPDATE asa_science_a
SET SPATIAL_BOUNDS = TO_GEOMETRIC_OBJECT(FOOTPRINT)
WHERE FOOTPRINT IS NOT NULL
AND FOOTPRINT <> ' ';

UPDATE asa_science_b
SET SPATIAL_BOUNDS = TO_GEOMETRIC_OBJECT(FOOTPRINT)     
WHERE FOOTPRINT IS NOT NULL
AND FOOTPRINT <> ' ';

-- Necessary to prepare Oracle for the Spatial Index coming.
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('ASA_SCIENCE_A','SPATIAL_BOUNDS', MDSYS.SDO_DIM_ARRAY(SDO_DIM_ELEMENT('RA', -360, 360, .0005), SDO_DIM_ELEMENT('DEC', -360, 360, .0005)), NULL);

-- Necessary to prepare Oracle for the Spatial Index coming.
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('ASA_SCIENCE_B','SPATIAL_BOUNDS', MDSYS.SDO_DIM_ARRAY(SDO_DIM_ELEMENT('RA', -360, 360, .0005), SDO_DIM_ELEMENT('DEC', -360, 360, .0005)), NULL);

-- Generate the Spatial Index.  Takes minutes to run.
CREATE INDEX SPATIAL_BOUNDS_IDX_A ON ASA_SCIENCE_A(SPATIAL_BOUNDS)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('layer_gtype=COLLECTION');

CREATE INDEX SPATIAL_BOUNDS_IDX_B ON ASA_SCIENCE_B(SPATIAL_BOUNDS)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS ('layer_gtype=COLLECTION');
